version: '3.8'

services:
  jane:
    build:
      context: .
      dockerfile: Dockerfile
    image: jane-mcp-server:1.0.0
    container_name: jane-mcp-server
    stdin_open: true # equivalent to docker run -i
    tty: true        # equivalent to docker run -t
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - JANE_DIR=/app/Jane
    volumes:
      # Mount the Jane directory for persistent storage
      # Replace /path/to/your/jane/data with your preferred host path
      - ${JANE_DATA_DIR:-/path/to/your/jane/data}:/app/Jane
    # Healthcheck to ensure the container is running properly
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s